# This is a basic workflow that is manually triggered

name: Manual Run automatic Maven Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      comment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Comment for release'
        # Default value if no value is explicitly provided
        default: 'Start release from WEB UI'
        # Input has to be provided for the workflow to run
        required: true

env:
  TECH_USER_USERNAME: 'innovitech-robot'
  TECH_USER_EMAIL: 'github-techuser@innovitech.hu'
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  mvn-release-main:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: speter555/gh-action-mvn-release-main@v0.25.0
        with:
          ARTIFACT_STORE_SERVER_ID: 'github'
          SETTINGS_XML_PATH: '.github/.m2/settings.xml'
          GPG_KEY_ID_GITHUB_TECHUSER: '${{ secrets.GPG_KEY_ID_GITHUB_TECHUSER }}'
          GPG_SIGNING_KEY_GITHUB_TECHUSER: '${{ secrets.GPG_SIGNING_KEY_GITHUB_TECHUSER }}'
          SSH_PRIVATE_KEY_GITHUB_TECHUSER: '${{ secrets.SSH_PRIVATE_KEY_GITHUB_TECHUSER }}'
          TECH_USER_USERNAME: '${{ env.TECH_USER_USERNAME }}'
          TECH_USER_PASSWORD: '${{ secrets.GITHUB_TOKEN }}'
          TECH_USER_EMAIL: '${{ env.TECH_USER_EMAIL }}'
          JAVA_VERSION: '17'
          JAVA_DISTRIBUTION: 'temurin'
